import 'package:flutter/material.dart';

final List<IconData> iconOptions = [
  Icons.list,
  Icons.star,
  Icons.coffee,
  Icons.shopping_cart,
  Icons.movie,
  Icons.fastfood,
  Icons.card_giftcard,
  Icons.local_offer,
  Icons.pets,
  Icons.sports_esports,
  Icons.bookmark,
  Icons.favorite,
  Icons.directions_car,
  Icons.home,
  Icons.school,
  Icons.flight,
  Icons.music_note,
  Icons.restaurant,
  Icons.local_cafe,
  Icons.local_florist,
  Icons.local_mall,
  Icons.local_play,
  Icons.local_pizza,
  Icons.local_taxi,
  Icons.beach_access,
  Icons.cake,
  Icons.child_friendly,
  Icons.directions_bike,
  Icons.directions_bus,
  Icons.directions_run,
  Icons.directions_walk,
  Icons.emoji_emotions,
  Icons.emoji_food_beverage,
  Icons.emoji_nature,
  Icons.emoji_objects,
  Icons.emoji_transportation,
];

final Map<int, IconData> iconMapping = {
  for (var icon in iconOptions) icon.codePoint: icon,
};
